language: csharp
mono: latest
script:
- msbuild
solution: All.sln
notifications:
  slack:
    on_failure: always
    on_pull_requests: true
    on_success: always
    rooms:
      secure: mVDu2NkTTQgSvvZB/tLOJdKUB3DPWVoYR0wFRamDgmSyyHhmjmxOPJBquvhzW5lchBOGBQ7SynT4KspuaHqwQgF5RBG+sXmP+Juu4JXt3uQiDq7X6nK/US1YXvIpsj3IgdhxcgAJDf61Q4aUwe88q4yTRmqgSrI7gF4P8945k3YJu25ElIWVrY7f4pmDttz11JuS7Bes9wY2/M2UcBEaTD0XMK6xSgxQQwffN2C8+FeaxbpcLXQ22Y17RQGPvOdLDNtvNADAtAJcATmhHjCNCDRT6Vrs5oQ5tZWdxnH3y/ZtH5cIyW9viJbMEGOZvWYcwM0S3wadKj5XkoGYo7ufQoLYEoDsa6KTKsNO95FwD2y1UQwqoEQtgB6SACYIlWZEr46CUTXPk+uKErfHdAE6ndTzI+fAE5PGovzEByQo6L5vY248VYQJd46Zel6MHqpcp8cIlngVetcSPpJ5/GtzD0pDfBBbhP2lcPLx+BNrnDt14EkikE8sPlNnmpMM3iE/ythPomvBzq/JFbEqfce0g+rem9VWqTZ+GyLXpdlUJBL0FCvxcBuOFxW+c8atfH9w4BJe9pVGs8xyuGQVoWzX6mAhIP0uRC5L4r7e5cZKSRhzByfVjd7S6mfV8O3oA2aqMfWrhkj+fNXrrb1KC0qrZyaaU+Jlv4MQgtN4MWsdD1Q=
